name: iw_logger
description: This project is an implementation that allow developers to encapsulate their own usage of a logger.
version: 1.0.1
repository: https://github.com/euivanw/iw_logger

topics:
  - logger

environment:
  sdk: ">=3.0.0 <4.0.0"

scripts: derry.yaml

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
